[package]
name = "simvcc"
version = "0.1.2"
edition = "2021"
authors = ["Cheng Maohua <cmh@seu.edu.cn>"]
description = "Vapor compression refrigeration cycle simulator in Rust"
license = "MIT"
homepage = "https://github.com/thermalogic/"
repository = "https://github.com/thermalogic/SimVCCE"
keywords = ["refrigeration", "simulation", "hvac"]
categories = ["science", "simulation"]
readme = "README.md"

[dependencies]
coolprop-sys = "7.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
