@startuml
vcc.VCCycle "1" *-[#blue]- "1" vcc.Connector 
vcc.VCCycle "1" o-- "1..*" components.Compressor 
vcc.VCCycle "1" o-- "1..*" components.Condenser
vcc.VCCycle "1" o-- "1..*" components.Evaporator
vcc.VCCycle "1" o-- "1..*" components.ExpansionValve

vcc.Connector "1" *-[#blue]- "2..*" components.Port
components.Compressor "1" *-[#blue]- "2" components.Port
components.ExpansionValve "1" *-[#blue]- "2" components.Port
components.Evaporator "1" *-[#blue]- "2" components.Port
components.Condenser "1" *-[#blue]- "2" components.Port

components.Device_SISO   <|-[#green]- components.Compressor
components.Device_SISO <|-[#green]-   components.Condenser
components.Device_SISO  <|-[#green]-  components.Evaporator
components.Device_SISO <|-[#green]-   components.ExpansionValve
@enduml
