@startuml
class Condenser {
    + {static} devtype: str
    + {static} energy: str
    + Qout: float
    + {static} Condenser(dictDev:dict)
    + state()
    + balance()
    + __str()__:str
}
Device_SISO  <|-up- Condenser
@enduml
