@startuml Port
class Port {
  + {static} cycle_refrigerant : str=R134a
  + {static} w : int
  + {static} title : str
  + {static} pairs : dict
  + refrigerant : str
  + index : int
  + p : float
  + t : float
  + x : float
  + h : float
  + s : float
  + mdot : float
  + stateok:bool
  + {static} Port(dictnode : dict)
  + state()
  + __str()__:str
}

class Connector {
  + nodes:Port[0..*]
  + {static} Connector(dictconnector : dict, comps : dict of the devices)
  - __combined_node_value(node : Port,port: Port)
  - __add_node(index,portpairs : tuple,comps)
}
Connector"1" *-- "2..*" Port

@enduml


