@startuml
class Connector {
  + nodes:Port[0..*]
  + {static} Connector(dictconnector : dict, comps : dict of the devices)
  - __combined_node_value(node : Port,port: Port)
  - __add_node(index,portpairs : tuple,comps)
}
@enduml


