@startuml
class Device_SISO {
  + {static} devtype: str
  + {static} energy: str
  + name: str
  + iPort: Port
  + oPort: Port
  + {static} Device_SISO(dictDev:dict)
  + state()
  + mass_balance()
  + balance()
  + __str()__:str
}
@enduml


