@startwbs
* SimVCCE
** <vccpython>
*** vccapp.py  **main app**\nvccapp_json.py  **main app using json**
*** <components> **port and devices classes**
**** port.py\ncompressor.py\n...       
*** <vcc> **the cycle analysis class and methods**
****  connector.py **the class Connector**\nvccobj.py **the class VCRCycle**\nutils.py **utils methods**
*** <vccmodel> **the dict of the cycle data**
****  *vcr*.py **the cycle dict**
*** <jsonmmodel> **json of the cycle flowchart and data**
****  *vcr*.py **the cycle json file**
*** <result> **result text files**
****  *.txt
@endwbs

