@startuml
class Evaporator {
    + {static} devtype: str
    + {static} energy: str
    + Qin: float
    + {static} Evaporator(dictDev:dict)
    + state()
    + balance()
    + __str()__:str
}
Device_SISO  <|-up- Evaporator
@enduml

     