@startuml
package components {
  class Port
  class Device_SISO
  class Compressor
  class Condenser
  class Evaporator
  class ExpansionValve
}
package vcc {
  class VCCycle
  class Connector
}
vcc ..> components : <<import>>
@enduml